name: CI - Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ] # DÃ©clenchement sur la branche main
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- BACKEND ---
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./BackendProject
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/BackendProject:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/BackendProject:${{ github.sha }}

      # --- FRONTEND ---
      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Gusto
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/Gusto:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/Gusto:${{ github.sha }}